name: Lint, Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src'
      - 'public'

jobs:
  checks:
    runs-on: ubuntu-latest
    name: Lint & build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install
        run: yarn install --immutable
      - name: Lint
        run: yarn lint
      - name: Build
        run: yarn build
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: rental-app
          path: build

  build:
    needs: [checks]
    runs-on: ubuntu-latest
    name: Deploying to surge
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: rental-app
          path: build
      - name: Install surge
        uses: actions/setup-node@v3
        with:
          node-version: 8
      - run: npm install -g surge
      - run: surge ./build https://rental-discovery.surge.sh --token ${{ secrets.SURGE_TOKEN }}
