name: E2E tests

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'cypress/**'
      - 'public/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code 🛎
        uses: actions/checkout@v3

      - name: Run E2E tests 🧪
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          start: npm start
